entry: gh-start
executions:
  - src:
      node: kiwi-gray-parrot
      port: exec
    dst:
      node: gray-mango-cherry
      port: exec
  - src:
      node: gray-mango-cherry
      port: exec
    dst:
      node: run-v1-cherry-raspberry-pineapple
      port: exec
  - src:
      node: gh-start
      port: exec-on-push
    dst:
      node: kiwi-gray-parrot
      port: exec
  - src:
      node: run-v1-cherry-raspberry-pineapple
      port: exec-success
    dst:
      node: run-v1-blackberry-green-snake
      port: exec
  - src:
      node: run-v1-blackberry-green-snake
      port: exec-success
    dst:
      node: github-com-actions-upload-artifact-v3-1-3-purple-rabbit-brown
      port: exec
connections: []
nodes:
  - id: gh-start
    type: gh-start@v1
    position:
      x: -490
      y: 1210
    settings:
      folded: false
  - id: kiwi-gray-parrot
    type: github.com/actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    position:
      x: 30
      y: 2110
    settings:
      folded: false
  - id: gray-mango-cherry
    type: github.com/actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
    position:
      x: 450
      y: 2080
    inputs:
      go-version: "1.22"
    settings:
      folded: false
  - id: run-v1-cherry-raspberry-pineapple
    type: run@v1
    position:
      x: 860
      y: 2110
    inputs:
      script: >-
        go mod tidy

        go vet

        go test ./... -v -race -coverpkg=./... -cover -coverprofile cover.out
        --tags=unit_tests,integration_tests,system_tests,github_impl

        go tool cover -html cover.out -o cover.html
    settings:
      folded: false
  - id: github-com-actions-upload-artifact-v3-1-3-purple-rabbit-brown
    type: >-
      github.com/actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
    position:
      x: 1580
      y: 2040
    inputs:
      name: cover
      path: cover.html
    settings:
      folded: false
  - id: run-v1-blackberry-green-snake
    type: run@v1
    position:
      x: 1210
      y: 2070
    inputs:
      script: go build --tags=github_impl .
    settings:
      folded: false
registries:
  - github.com/docker/build-push-action@v5.1.0
  - github.com/docker/login-action@v3.0.0
  - github.com/docker/setup-buildx-action@v3.0.0
description: ""
