entry: gh-start
executions:
  - src:
      node: kiwi-gray-parrot
      port: exec
    dst:
      node: gray-mango-cherry
      port: exec
  - src:
      node: gray-mango-cherry
      port: exec
    dst:
      node: penguin-dog-blueberry
      port: exec
  - src:
      node: gh-start
      port: exec-on-push
    dst:
      node: kiwi-gray-parrot
      port: exec
  - src:
      node: blue-monkey-tiger
      port: exec
    dst:
      node: penguin-coconut-gray
      port: exec
  - src:
      node: blue-monkey-tiger
      port: exec[0]
    dst:
      node: penguin-coconut-gray
      port: exec
  - src:
      node: blue-monkey-tiger
      port: exec[1]
    dst:
      node: yellow-kangaroo-pineapple
      port: exec
  - src:
      node: blue-monkey-tiger
      port: exec[2]
    dst:
      node: giraffe-monkey-plum
      port: exec
  - src:
      node: giraffe-monkey-plum
      port: exec-success
    dst:
      node: orange-watermelon-lion
      port: exec
  - src:
      node: yellow-kangaroo-pineapple
      port: exec-success
    dst:
      node: blueberry-lemon-orange
      port: exec
  - src:
      node: penguin-coconut-gray
      port: exec-success
    dst:
      node: rabbit-dolphin-raspberry
      port: exec
  - src:
      node: penguin-dog-blueberry
      port: exec-success
    dst:
      node: branch-v1-pink-purple-koala
      port: exec
  - src:
      node: branch-v1-pink-purple-koala
      port: exec-then
    dst:
      node: blue-monkey-tiger
      port: exec
  - src:
      node: branch-v1-pink-purple-koala
      port: exec-otherwise
    dst:
      node: run-v1-cherry-raspberry-pineapple
      port: exec
connections:
  - src:
      node: env-get-v1-rabbit-octopus-gold
      port: env
    dst:
      node: string-match-v1-pomegranate-raspberry-silver
      port: str1
  - src:
      node: string-match-v1-pomegranate-raspberry-silver
      port: result
    dst:
      node: branch-v1-pink-purple-koala
      port: condition
nodes:
  - id: gh-start
    type: gh-start@v1
    position:
      x: 10
      y: 10
    settings:
      folded: true
  - id: kiwi-gray-parrot
    type: github.com/actions/checkout
    position:
      x: 260
      y: 990
    settings:
      folded: false
  - id: gray-mango-cherry
    type: github.com/actions/setup-go
    position:
      x: 660
      y: 950
    inputs:
      go-version: '1.21'
    settings:
      folded: false
  - id: penguin-coconut-gray
    type: run@v1
    position:
      x: 2030
      y: 740
    inputs:
      script: |-
        GOOS=linux GOARCH=amd64 go build -o dist-linux/graph-runner-linux-x64 .
        tar -cvf graph-runner-linux.tar -C dist-linux .
    settings:
      folded: false
  - id: rabbit-dolphin-raspberry
    type: github.com/actions/upload-artifact@v3.1.3
    position:
      x: 2320
      y: 740
    inputs:
      name: graph-runner-linux-x64
      path: graph-runner-linux.tar
    settings:
      folded: false
  - id: yellow-kangaroo-pineapple
    type: run@v1
    position:
      x: 2030
      y: 1080
    inputs:
      script: >-
        GOOS=windows GOARCH=amd64 go build -tags=github_impl -o
        dist-windows/graph-runner-windows-x64.exe .
    settings:
      folded: false
  - id: blueberry-lemon-orange
    type: github.com/actions/upload-artifact@v3.1.3
    position:
      x: 2320
      y: 1080
    inputs:
      name: graph-runner-windows-x64
      path: dist-windows/graph-runner-windows-x64.exe
    settings:
      folded: false
  - id: penguin-dog-blueberry
    type: run@v1
    position:
      x: 1060
      y: 860
    inputs:
      script: |-
        go mod tidy
        go vet
    settings:
      folded: false
  - id: giraffe-monkey-plum
    type: run@v1
    position:
      x: 2030
      y: 1420
    inputs:
      script: >-
        GOOS=darwin GOARCH=arm64 go build -tags=github_impl -o
        dist-macos/graph-runner-macos-arm64 .

        GOOS=darwin GOARCH=amd64 go build -tags=github_impl -o
        dist-macos/graph-runner-macos-x64 .

        tar -cvf graph-runner-macos.tar -C dist-macos .
    settings:
      folded: false
  - id: orange-watermelon-lion
    type: github.com/actions/upload-artifact@v3.1.3
    position:
      x: 2320
      y: 1420
    inputs:
      name: graph-runner-macos
      path: graph-runner-macos.tar
    settings:
      folded: false
  - id: blue-monkey-tiger
    type: parallel-exec@v1
    position:
      x: 1720
      y: 970
    outputs:
      exec[0]: ''
      exec[1]: ''
      exec[2]: ''
    settings:
      folded: false
  - id: env-get-v1-rabbit-octopus-gold
    type: env-get@v1
    position:
      x: 790
      y: 1370
    inputs:
      env: GITHUB_REF
    settings:
      folded: false
  - id: string-match-v1-pomegranate-raspberry-silver
    type: string-match@v1
    position:
      x: 1050
      y: 1380
    inputs:
      op: startswith
      str2: refs/tags/
    settings:
      folded: false
  - id: branch-v1-pink-purple-koala
    type: branch@v1
    position:
      x: 1410
      y: 1110
    settings:
      folded: false
  - id: run-v1-cherry-raspberry-pineapple
    type: run@v1
    position:
      x: 1650
      y: 1140
    inputs:
      script: >-
        go vet

        go test ./... -v -race -coverpkg=./... -cover -coverprofile cover.out
        --tags=unit_tests,integration_tests,system_tests,github_impl
    settings:
      folded: false
registries:
  - github.com/actions/upload-artifact@v3.1.3
description: ''
