entry: gh-start
executions:
  - src:
      node: blue-monkey-tiger
      port: exec
    dst:
      node: penguin-coconut-gray
      port: exec
  - src:
      node: blue-monkey-tiger
      port: exec[0]
    dst:
      node: penguin-coconut-gray
      port: exec
  - src:
      node: blue-monkey-tiger
      port: exec[1]
    dst:
      node: yellow-kangaroo-pineapple
      port: exec
  - src:
      node: blue-monkey-tiger
      port: exec[2]
    dst:
      node: giraffe-monkey-plum
      port: exec
  - src:
      node: giraffe-monkey-plum
      port: exec-success
    dst:
      node: orange-watermelon-lion
      port: exec
  - src:
      node: yellow-kangaroo-pineapple
      port: exec-success
    dst:
      node: blueberry-lemon-orange
      port: exec
  - src:
      node: penguin-coconut-gray
      port: exec-success
    dst:
      node: rabbit-dolphin-raspberry
      port: exec
  - src:
      node: parallel-exec-v1-cranberry-blueberry-orange
      port: exec[0]
    dst:
      node: github-com-docker-login-action-v3-0-0-kiwi-giraffe-kiwi
      port: exec
  - src:
      node: parallel-exec-v1-cranberry-blueberry-orange
      port: exec[1]
    dst:
      node: blue-monkey-tiger
      port: exec
  - src:
      node: gh-start
      port: exec-on-push
    dst:
      node: branch-v1-pink-purple-koala
      port: exec
  - src:
      node: branch-v1-pink-purple-koala
      port: exec-then
    dst:
      node: parallel-exec-v1-cranberry-blueberry-orange
      port: exec
  - src:
      node: github-com-docker-login-action-v3-0-0-kiwi-giraffe-kiwi
      port: exec
    dst:
      node: github-com-docker-setup-buildx-action-v3-0-0-silver-koala-lemon
      port: exec
  - src:
      node: github-com-docker-setup-buildx-action-v3-0-0-silver-koala-lemon
      port: exec
    dst:
      node: github-com-docker-build-push-action-v5-1-0-brown-orange-banana
      port: exec
connections:
  - src:
      node: env-get-v1-rabbit-octopus-gold
      port: env
    dst:
      node: string-match-v1-pomegranate-raspberry-silver
      port: str1
  - src:
      node: string-match-v1-pomegranate-raspberry-silver
      port: result
    dst:
      node: branch-v1-pink-purple-koala
      port: condition
  - src:
      node: env-get-v1-strawberry-banana-cranberry
      port: env
    dst:
      node: string-fmt-v1-giraffe-gray-plum
      port: input[0]
  - src:
      node: env-get-v1-strawberry-banana-cranberry
      port: env
    dst:
      node: string-fmt-v1-dolphin-monkey-grape
      port: input[0]
  - src:
      node: env-get-v1-strawberry-banana-cranberry
      port: env
    dst:
      node: string-fmt-v1-squirrel-strawberry-plum
      port: input[0]
  - src:
      node: string-fmt-v1-dolphin-monkey-grape
      port: result
    dst:
      node: orange-watermelon-lion
      port: name
  - src:
      node: string-fmt-v1-giraffe-gray-plum
      port: result
    dst:
      node: blueberry-lemon-orange
      port: name
  - src:
      node: string-fmt-v1-squirrel-strawberry-plum
      port: result
    dst:
      node: rabbit-dolphin-raspberry
      port: name
  - src:
      node: string-fmt-v1-shark-orange-brown
      port: result
    dst:
      node: github-com-docker-build-push-action-v5-1-0-brown-orange-banana
      port: tags
  - src:
      node: env-get-v1-gold-panda-coconut
      port: env
    dst:
      node: string-fmt-v1-shark-orange-brown
      port: input[0]
  - src:
      node: env-get-v1-gold-panda-coconut
      port: env
    dst:
      node: string-fmt-v1-shark-orange-brown
      port: input[1]
  - src:
      node: env-get-v1-penguin-pineapple-pear
      port: env
    dst:
      node: string-fmt-v1-shark-orange-brown
      port: input[2]
nodes:
  - id: gh-start
    type: gh-start@v1
    position:
      x: 70
      y: 1090
    settings:
      folded: true
  - id: penguin-coconut-gray
    type: run@v1
    position:
      x: 1640
      y: 1520
    inputs:
      script: >-
        GOOS=linux GOARCH=amd64 go build -ldflags "-X
        actionforge/graph-runner/core.Production=true -X
        actionforge/graph-runner/core.Version=$GITHUB_REF_NAME"
        -tags=github_impl -o dist-linux/graph-runner-linux-x64 .

        tar -cvf graph-runner-linux.tar -C dist-linux .
    settings:
      folded: false
  - id: rabbit-dolphin-raspberry
    type: >-
      github.com/actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
    position:
      x: 2060
      y: 1980
    inputs:
      name: graph-runner-linux-x64
      path: graph-runner-linux.tar
    settings:
      folded: false
  - id: yellow-kangaroo-pineapple
    type: run@v1
    position:
      x: 1640
      y: 1860
    inputs:
      script: >-
        GOOS=windows GOARCH=amd64 go build -ldflags "-X
        actionforge/graph-runner/core.Production=true -X
        actionforge/graph-runner/core.Version=$GITHUB_REF_NAME"
        -tags=github_impl -o dist-windows/graph-runner-windows-x64.exe .
    settings:
      folded: false
  - id: blueberry-lemon-orange
    type: >-
      github.com/actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
    position:
      x: 2060
      y: 2280
    inputs:
      name: graph-runner-windows-x64
      path: dist-windows/graph-runner-windows-x64.exe
    settings:
      folded: false
  - id: giraffe-monkey-plum
    type: run@v1
    position:
      x: 1640
      y: 2190
    inputs:
      script: >-
        GOOS=darwin GOARCH=arm64 go build -ldflags "-X
        actionforge/graph-runner/core.Production=true -X
        actionforge/graph-runner/core.Version=$GITHUB_REF_NAME"
        -tags=github_impl -o dist-macos/graph-runner-macos-arm64 .

        GOOS=darwin GOARCH=amd64 go build -ldflags "-X
        actionforge/graph-runner/core.Production=true -X
        actionforge/graph-runner/core.Version=$GITHUB_REF_NAME"
        -tags=github_impl -o dist-macos/graph-runner-macos-x64 .

        tar -cvf graph-runner-macos.tar -C dist-macos .
    settings:
      folded: false
  - id: orange-watermelon-lion
    type: >-
      github.com/actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
    position:
      x: 2060
      y: 2580
    inputs:
      name: graph-runner-macos
      path: graph-runner-macos.tar
    settings:
      folded: false
  - id: blue-monkey-tiger
    type: parallel-exec@v1
    position:
      x: 1310
      y: 1890
    outputs:
      exec[0]: ""
      exec[1]: ""
      exec[2]: ""
    settings:
      folded: false
  - id: env-get-v1-rabbit-octopus-gold
    type: env-get@v1
    position:
      x: 30
      y: 1300
    inputs:
      env: GITHUB_REF
    settings:
      folded: false
  - id: string-match-v1-pomegranate-raspberry-silver
    type: string-match@v1
    position:
      x: 290
      y: 1310
    inputs:
      op: startswith
      str2: refs/tags/
    settings:
      folded: false
  - id: branch-v1-pink-purple-koala
    type: branch@v1
    position:
      x: 650
      y: 1140
    settings:
      folded: false
  - id: parallel-exec-v1-cranberry-blueberry-orange
    type: parallel-exec@v1
    position:
      x: 860
      y: 1100
    outputs:
      exec[0]: ""
      exec[1]: ""
    settings:
      folded: false
  - id: string-fmt-v1-squirrel-strawberry-plum
    type: string-fmt@v1
    position:
      x: 1610
      y: 2520
    inputs:
      input[0]: null
      fmt: graph-runner-linux-%v.tar
    settings:
      folded: false
  - id: string-fmt-v1-giraffe-gray-plum
    type: string-fmt@v1
    position:
      x: 1610
      y: 2730
    inputs:
      input[0]: null
      fmt: graph-runner-windows-x64-%v
    settings:
      folded: false
  - id: string-fmt-v1-dolphin-monkey-grape
    type: string-fmt@v1
    position:
      x: 1610
      y: 2940
    inputs:
      input[0]: null
      fmt: graph-runner-macos-%v.tar
    settings:
      folded: false
  - id: env-get-v1-strawberry-banana-cranberry
    type: env-get@v1
    position:
      x: 1280
      y: 2840
    inputs:
      env: GITHUB_REF_NAME
    settings:
      folded: false
  - id: github-com-docker-build-push-action-v5-1-0-brown-orange-banana
    type: >-
      github.com/docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56
    position:
      x: 2060
      y: 800
    inputs:
      push: "true"
      context: .
    settings:
      folded: false
  - id: string-fmt-v1-shark-orange-brown
    type: string-fmt@v1
    position:
      x: 1610
      y: 1130
    inputs:
      input[0]: ""
      fmt: ghcr.io/%v:latest,ghcr.io/%v:%v
      input[1]: null
      input[2]: null
    settings:
      folded: false
  - id: github-com-docker-login-action-v3-0-0-kiwi-giraffe-kiwi
    type: github.com/docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
    position:
      x: 1220
      y: 560
    inputs:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
    settings:
      folded: false
  - id: env-get-v1-gold-panda-coconut
    type: env-get@v1
    position:
      x: 1280
      y: 1160
    inputs:
      env: GITHUB_REPOSITORY
    settings:
      folded: false
  - id: env-get-v1-penguin-pineapple-pear
    type: env-get@v1
    position:
      x: 1280
      y: 1260
    inputs:
      env: GITHUB_REF_NAME
    settings:
      folded: false
  - id: github-com-docker-setup-buildx-action-v3-0-0-silver-koala-lemon
    type: >-
      github.com/docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226
    position:
      x: 1610
      y: 450
    inputs:
      platforms: linux/amd64,linux/arm64,linux/arm/v7
    settings:
      folded: false
registries:
  - github.com/docker/build-push-action@v5.1.0
  - github.com/docker/login-action@v3.0.0
  - github.com/docker/setup-buildx-action@v3.0.0
description: ""
