entry: start
executions:
  - src:
      node: start
      port: exec
    dst:
      node: run-v1-apple-silver-lion
      port: exec
  - src:
      node: gh-actionforge-test-action-node-main-lemon-penguin-yellow
      port: exec
    dst:
      node: run-v1-giraffe-grape-zebra
      port: exec
  - src:
      node: run-v1-apple-silver-lion
      port: exec-success
    dst:
      node: parallel-exec-v1-blackberry-orange-coconut
      port: exec
  - src:
      node: parallel-exec-v1-blackberry-orange-coconut
      port: exec[0]
    dst:
      node: gh-actionforge-test-action-node-main-lemon-penguin-yellow
      port: exec
  - src:
      node: parallel-exec-v1-blackberry-orange-coconut
      port: exec[1]
    dst:
      node: gh-actionforge-test-action-node-main-blueberry-monkey-plum
      port: exec
  - src:
      node: gh-actionforge-test-action-node-main-blueberry-monkey-plum
      port: exec
    dst:
      node: run-v1-pink-brown-kangaroo
      port: exec
connections:
  - src:
      node: start
      port: env
    dst:
      node: run-v1-apple-silver-lion
      port: env
nodes:
  - id: start
    type: start@v1
    position:
      x: 10
      y: 430
    settings:
      folded: false
  - id: gh-actionforge-test-action-node-main-lemon-penguin-yellow
    type: >-
      github.com/actionforge/test-action-node@bbba31994bb85344bc7725ed195b4c44f10162b2
    position:
      x: 770
      y: 100
    inputs:
      input1: lorem
    settings:
      folded: false
  - id: run-v1-apple-silver-lion
    type: run@v1
    position:
      x: 230
      y: 310
    inputs:
      script: |
        input1="hello world"

        if [ "$MY_ENV" == "$input1" ]; then
            echo "MY_ENV correctly set to $input1"
        else
            echo "MY_ENV is not correctly set, got: '$MY_ENV'"
            exit 1
        fi
    settings:
      folded: false
  - id: run-v1-giraffe-grape-zebra
    type: run@v1
    position:
      x: 1080
      y: 10
    inputs:
      script: >
        input1="lorem"


        if [ "$MY_ENV" == "this env modified by test-action-node and input1
        value is '$input1'" ]; then
            echo "MY_ENV correctly contains $input1"
        else
            echo "MY_ENV is not correctly set, got: '$MY_ENV'"
            exit 1
        fi
    settings:
      folded: false
  - id: gh-actionforge-test-action-node-main-blueberry-monkey-plum
    type: >-
      github.com/actionforge/test-action-node@bbba31994bb85344bc7725ed195b4c44f10162b2
    position:
      x: 770
      y: 430
    inputs:
      input1: ipsum
    settings:
      folded: false
  - id: parallel-exec-v1-blackberry-orange-coconut
    type: parallel-exec@v1
    position:
      x: 540
      y: 270
    outputs:
      exec[0]: ""
      exec[1]: ""
    settings:
      folded: false
  - id: run-v1-pink-brown-kangaroo
    type: run@v1
    position:
      x: 1080
      y: 340
    inputs:
      script: >
        input1="ipsum"


        if [ "$MY_ENV" == "this env modified by test-action-node and input1
        value is '$input1'" ]; then
            echo "MY_ENV correctly contains $input1"
        else
            echo "MY_ENV is not correctly set, got: '$MY_ENV'"
            exit 1
        fi
    settings:
      folded: false
registries:
  - github.com/actionforge/test-action-node@main
description: ""
