// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Wait For


// ==> (o) Inputs

// 
const Wait_for_v1_Input_after core.InputId = "after"
// 
const Wait_for_v1_Input_exec core.InputId = "exec"
// 
const Wait_for_v1_Input_loop core.InputId = "loop"


// Outputs (o) ==> 

// 
const Wait_for_v1_Output_exec core.OutputId = "exec"


