// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Negate the input.


// ==> (o) Inputs

// 
const Negate_v1_Input_input core.InputId = "input"


// Outputs (o) ==> 

// 
const Negate_v1_Output_result core.OutputId = "result"


