// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// String Format


// ==> (o) Inputs

// 
const String_fmt_v1_Input_fmt core.InputId = "fmt"
// 
const String_fmt_v1_Input_input core.InputId = "input"


// Outputs (o) ==> 

// Formatted String
const String_fmt_v1_Output_result core.OutputId = "result"


