// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Parallel For Loop


// ==> (o) Inputs

// 
const Parallel_for_v1_Input_exec core.InputId = "exec"
// 
const Parallel_for_v1_Input_first_index core.InputId = "first_index"
// 
const Parallel_for_v1_Input_last_index core.InputId = "last_index"


// Outputs (o) ==> 

// 
const Parallel_for_v1_Output_exec_body core.OutputId = "exec-body"
// Finish
const Parallel_for_v1_Output_exec_finish core.OutputId = "exec-finish"
// Current iteration
const Parallel_for_v1_Output_index core.OutputId = "index"


