// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Perform a join operation on a file path


// ==> (o) Inputs

// 
const Filepath_join_v1_Input_paths core.InputId = "paths"


// Outputs (o) ==> 

// 
const Filepath_join_v1_Output_result core.OutputId = "result"


