// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Iterators are a way to walk through an array or map


// ==> (o) Inputs

// 
const Iterator_v1_Input_array core.InputId = "array"
// 
const Iterator_v1_Input_exec core.InputId = "exec"


// Outputs (o) ==> 

// 
const Iterator_v1_Output_exec core.OutputId = "exec"
// The index of the item
const Iterator_v1_Output_key core.OutputId = "key"
// The value of the item
const Iterator_v1_Output_value core.OutputId = "value"


