// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Group Node


// ==> (o) Inputs

// 
const Subgraph_v1_Input_exec core.InputId = "exec"


// Outputs (o) ==> 

// 
const Subgraph_v1_Output_exec core.OutputId = "exec"


