// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Perform operations on filepaths.


// ==> (o) Inputs

// 
const Filepath_op_v1_Input_op core.InputId = "op"
// 
const Filepath_op_v1_Input_path core.InputId = "path"


// Outputs (o) ==> 

// 
const Filepath_op_v1_Output_result core.OutputId = "result"


