// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Node to list objects in an S3 bucket directory.


// ==> (o) Inputs

// 
const Aws_s3_list_v1_Input_bucket core.InputId = "bucket"
// A delimiter is a character you use to group keys.
const Aws_s3_list_v1_Input_delimiter core.InputId = "delimiter"
// 
const Aws_s3_list_v1_Input_exec core.InputId = "exec"
// The directory prefix for the S3 bucket. If not specified, lists all objects in the bucket.
const Aws_s3_list_v1_Input_prefix core.InputId = "prefix"


// Outputs (o) ==> 

// 
const Aws_s3_list_v1_Output_exec core.OutputId = "exec"
// The list of items in the specified S3 directory.
const Aws_s3_list_v1_Output_items core.OutputId = "items"


