// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Test node for integration tests


// ==> (o) Inputs

// 
const Test_v1_Input_input_any core.InputId = "input-any"
// 
const Test_v1_Input_input_array_bool core.InputId = "input-array-bool"
// 
const Test_v1_Input_input_array_number core.InputId = "input-array-number"
// 
const Test_v1_Input_input_array_string core.InputId = "input-array-string"
// 
const Test_v1_Input_input_bool core.InputId = "input-bool"
// 
const Test_v1_Input_input_map_string_int32 core.InputId = "input-map-string-int32"
// 
const Test_v1_Input_input_number core.InputId = "input-number"
// 
const Test_v1_Input_input_string core.InputId = "input-string"


// Outputs (o) ==> 

// 
const Test_v1_Output_output_any core.OutputId = "output-any"
// 
const Test_v1_Output_output_array_bool core.OutputId = "output-array-bool"
// 
const Test_v1_Output_output_array_number core.OutputId = "output-array-number"
// 
const Test_v1_Output_output_array_string core.OutputId = "output-array-string"
// 
const Test_v1_Output_output_bool core.OutputId = "output-bool"
// 
const Test_v1_Output_output_map_string_int32 core.OutputId = "output-map-string-int32"
// 
const Test_v1_Output_output_number core.OutputId = "output-number"
// 
const Test_v1_Output_output_string core.OutputId = "output-string"


