// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Constant value of a number


// ==> (o) Inputs

// 
const Const_number_v1_Input_input core.InputId = "input"


// Outputs (o) ==> 

// 
const Const_number_v1_Output_result core.OutputId = "result"


