// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Convert the input to a string.


// ==> (o) Inputs

// 
const Cast_string_v1_Input_value core.InputId = "value"


// Outputs (o) ==> 

// 
const Cast_string_v1_Output_output core.OutputId = "output"


