// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Read a file from the file system via a stream.


// ==> (o) Inputs

// 
const File_read_stream_v1_Input_exec core.InputId = "exec"
// 
const File_read_stream_v1_Input_path core.InputId = "path"


// Outputs (o) ==> 

// 
const File_read_stream_v1_Output_exec core.OutputId = "exec"
// 
const File_read_stream_v1_Output_stream core.OutputId = "stream"


