// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Run code


// ==> (o) Inputs

// 
const Run_v1_Input_env core.InputId = "env"
// 
const Run_v1_Input_exec core.InputId = "exec"
// 
const Run_v1_Input_print core.InputId = "print"
// 
const Run_v1_Input_script core.InputId = "script"
// 
const Run_v1_Input_shell core.InputId = "shell"


// Outputs (o) ==> 

// 
const Run_v1_Output_exec_err core.OutputId = "exec_err"
// 
const Run_v1_Output_exec_success core.OutputId = "exec_success"
// 
const Run_v1_Output_exit_code core.OutputId = "exit_code"
// 
const Run_v1_Output_output core.OutputId = "output"


