// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// A node to read Github Secrets.


// ==> (o) Inputs

// The name of the GitHub workflow secret.
const Gh_secret_v1_Input_name core.InputId = "name"
// A prefix for the secret, specifically used to easier construct environment variables.
const Gh_secret_v1_Input_prefix core.InputId = "prefix"


// Outputs (o) ==> 

// The value of the GitHub workflow secret.
const Gh_secret_v1_Output_secret core.OutputId = "secret"


