// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Match a string against a certain operation.


// ==> (o) Inputs

// 
const String_match_v1_Input_op core.InputId = "op"
// 
const String_match_v1_Input_str1 core.InputId = "str1"
// 
const String_match_v1_Input_str2 core.InputId = "str2"


// Outputs (o) ==> 

// Current iteration
const String_match_v1_Output_result core.OutputId = "result"


