// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Write a file to the file system.


// ==> (o) Inputs

// 
const File_write_v1_Input_content core.InputId = "content"
// 
const File_write_v1_Input_exec core.InputId = "exec"
// 
const File_write_v1_Input_path core.InputId = "path"


// Outputs (o) ==> 

// 
const File_write_v1_Output_exec core.OutputId = "exec"
// 
const File_write_v1_Output_exec_err core.OutputId = "exec-err"


