// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// A node that is able to execute javascript code.


// Outputs (o) ==> 

// Execute actions when a branch protection rule is triggered
const Gh_start_v1_Output_exec_on_branch_protection_rule core.OutputId = "exec-on-branch_protection_rule"
// Execute actions when a check run is triggered
const Gh_start_v1_Output_exec_on_check_run core.OutputId = "exec-on-check_run"
// Execute actions when a check suite is triggered
const Gh_start_v1_Output_exec_on_check_suite core.OutputId = "exec-on-check_suite"
// Execute actions when a new resource is created
const Gh_start_v1_Output_exec_on_create core.OutputId = "exec-on-create"
// Execute actions when a resource is deleted
const Gh_start_v1_Output_exec_on_delete core.OutputId = "exec-on-delete"
// Execute actions when a deployment is triggered
const Gh_start_v1_Output_exec_on_deployment core.OutputId = "exec-on-deployment"
// Execute actions when a deployment status is triggered
const Gh_start_v1_Output_exec_on_deployment_status core.OutputId = "exec-on-deployment_status"
// Execute actions when a discussion is triggered
const Gh_start_v1_Output_exec_on_discussion core.OutputId = "exec-on-discussion"
// Execute actions when a discussion comment is triggered
const Gh_start_v1_Output_exec_on_discussion_comment core.OutputId = "exec-on-discussion_comment"
// Execute actions when a repository is forked
const Gh_start_v1_Output_exec_on_fork core.OutputId = "exec-on-fork"
// Execute actions when a Gollum event is triggered
const Gh_start_v1_Output_exec_on_gollum core.OutputId = "exec-on-gollum"
// Execute actions when an issue comment is triggered
const Gh_start_v1_Output_exec_on_issue_comment core.OutputId = "exec-on-issue_comment"
// Execute actions when an issue is triggered
const Gh_start_v1_Output_exec_on_issues core.OutputId = "exec-on-issues"
// Execute actions when a label is triggered
const Gh_start_v1_Output_exec_on_label core.OutputId = "exec-on-label"
// Execute actions when a merge group is triggered
const Gh_start_v1_Output_exec_on_merge_group core.OutputId = "exec-on-merge_group"
// Execute actions when a milestone is triggered
const Gh_start_v1_Output_exec_on_milestone core.OutputId = "exec-on-milestone"
// Execute actions when a page build is triggered
const Gh_start_v1_Output_exec_on_page_build core.OutputId = "exec-on-page_build"
// Execute actions when a project is triggered
const Gh_start_v1_Output_exec_on_project core.OutputId = "exec-on-project"
// Execute actions when a project card is triggered
const Gh_start_v1_Output_exec_on_project_card core.OutputId = "exec-on-project_card"
// Execute actions when a project column is triggered
const Gh_start_v1_Output_exec_on_project_column core.OutputId = "exec-on-project_column"
// Execute actions when a repository is made public
const Gh_start_v1_Output_exec_on_public core.OutputId = "exec-on-public"
// Execute actions when a pull request is triggered
const Gh_start_v1_Output_exec_on_pull_request core.OutputId = "exec-on-pull_request"
// Execute actions when a pull request comment is triggered
const Gh_start_v1_Output_exec_on_pull_request_comment core.OutputId = "exec-on-pull_request_comment"
// Execute actions when a pull request review is triggered
const Gh_start_v1_Output_exec_on_pull_request_review core.OutputId = "exec-on-pull_request_review"
// Execute actions when a pull request review comment is triggered
const Gh_start_v1_Output_exec_on_pull_request_review_comment core.OutputId = "exec-on-pull_request_review_comment"
// Execute actions when a pull request target is triggered
const Gh_start_v1_Output_exec_on_pull_request_target core.OutputId = "exec-on-pull_request_target"
// Execute actions when a push event is triggered
const Gh_start_v1_Output_exec_on_push core.OutputId = "exec-on-push"
// Execute actions when a registry package is triggered
const Gh_start_v1_Output_exec_on_registry_package core.OutputId = "exec-on-registry_package"
// Execute actions when a release is triggered
const Gh_start_v1_Output_exec_on_release core.OutputId = "exec-on-release"
// Execute actions when a repository dispatch is triggered
const Gh_start_v1_Output_exec_on_repository_dispatch core.OutputId = "exec-on-repository_dispatch"
// Execute actions when a scheduled event is triggered
const Gh_start_v1_Output_exec_on_schedule core.OutputId = "exec-on-schedule"
// Execute actions when a status is triggered
const Gh_start_v1_Output_exec_on_status core.OutputId = "exec-on-status"
// Execute actions when a repository is watched
const Gh_start_v1_Output_exec_on_watch core.OutputId = "exec-on-watch"
// Execute actions when a workflow call is triggered
const Gh_start_v1_Output_exec_on_workflow_call core.OutputId = "exec-on-workflow_call"
// Execute actions when a workflow dispatch is triggered
const Gh_start_v1_Output_exec_on_workflow_dispatch core.OutputId = "exec-on-workflow_dispatch"
// Execute actions when a workflow run is triggered
const Gh_start_v1_Output_exec_on_workflow_run core.OutputId = "exec-on-workflow_run"


