// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Platform Switch


// ==> (o) Inputs

// 
const Switch_platform_v1_Input_exec core.InputId = "exec"


// Outputs (o) ==> 

// 
const Switch_platform_v1_Output_exec_linux core.OutputId = "exec-linux"
// 
const Switch_platform_v1_Output_exec_macos core.OutputId = "exec-macos"
// 
const Switch_platform_v1_Output_exec_win core.OutputId = "exec-win"


