// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Constant value of a bool


// ==> (o) Inputs

// 
const Const_bool_v1_Input_input core.InputId = "input"


// Outputs (o) ==> 

// 
const Const_bool_v1_Output_result core.OutputId = "result"


