// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Node to make HTTP requests


// ==> (o) Inputs

// 
const Http_v1_Input_exec core.InputId = "exec"
// 
const Http_v1_Input_header core.InputId = "header"
// 
const Http_v1_Input_method core.InputId = "method"
// 
const Http_v1_Input_url core.InputId = "url"


// Outputs (o) ==> 

// 
const Http_v1_Output_body core.OutputId = "body"
// 
const Http_v1_Output_exec core.OutputId = "exec"
// 
const Http_v1_Output_http_status core.OutputId = "http_status"


