// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Conditional Branch


// ==> (o) Inputs

// Condition to execute either if or else.
const Branch_v1_Input_condition core.InputId = "condition"
// 
const Branch_v1_Input_exec core.InputId = "exec"


// Outputs (o) ==> 

// 
const Branch_v1_Output_otherwise core.OutputId = "otherwise"
// 
const Branch_v1_Output_then core.OutputId = "then"


