// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Walks through a directory and executes a body for each file


// ==> (o) Inputs

// The directory to walk
const Dirwalk_v1_Input_dir core.InputId = "dir"
// 
const Dirwalk_v1_Input_exec core.InputId = "exec"
// The glob to match
const Dirwalk_v1_Input_glob core.InputId = "glob"


// Outputs (o) ==> 

// 
const Dirwalk_v1_Output_exec core.OutputId = "exec"
// The items that were walked
const Dirwalk_v1_Output_items core.OutputId = "items"


