// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Returns the length of the input


// ==> (o) Inputs

// 
const Length_v1_Input_input core.InputId = "input"


// Outputs (o) ==> 

// 
const Length_v1_Output_result core.OutputId = "result"


