// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Apply the XOR operator on two or more boolean values.


// ==> (o) Inputs

// 
const Bool_xor_v1_Input_input core.InputId = "input"


// Outputs (o) ==> 

// 
const Bool_xor_v1_Output_result core.OutputId = "result"


