// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// A node that is able to execute javascript code.


// Outputs (o) ==> 

// 
const Start_v1_Output_exec core.OutputId = "exec"


