// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Arch Switch


// ==> (o) Inputs

// 
const Switch_arch_v1_Input_exec core.InputId = "exec"


// Outputs (o) ==> 

// 
const Switch_arch_v1_Output_exec_arm32 core.OutputId = "exec-arm32"
// 
const Switch_arch_v1_Output_exec_arm64 core.OutputId = "exec-arm64"
// 
const Switch_arch_v1_Output_exec_x64 core.OutputId = "exec-x64"


