// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Node to upload an object to an S3 bucket.


// ==> (o) Inputs

// 
const Aws_s3_upload_v1_Input_bucket core.InputId = "bucket"
// 
const Aws_s3_upload_v1_Input_content core.InputId = "content"
// 
const Aws_s3_upload_v1_Input_exec core.InputId = "exec"
// 
const Aws_s3_upload_v1_Input_name core.InputId = "name"


// Outputs (o) ==> 

// 
const Aws_s3_upload_v1_Output_exec core.OutputId = "exec"


