// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// List of environment variables.


// ==> (o) Inputs

// 
const Env_array_v1_Input_env core.InputId = "env"


// Outputs (o) ==> 

// 
const Env_array_v1_Output_env core.OutputId = "env"


