// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Execute a set of tasks in parallel with a multi-queue.


// ==> (o) Inputs

// 
const Parallel_multi_queue_v1_Input_context core.InputId = "context"
// 
const Parallel_multi_queue_v1_Input_exec core.InputId = "exec"
// 
const Parallel_multi_queue_v1_Input_worker_count core.InputId = "worker_count"


// Outputs (o) ==> 

// 
const Parallel_multi_queue_v1_Output_context core.OutputId = "context"
// 
const Parallel_multi_queue_v1_Output_exec_body core.OutputId = "exec-body"


