// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Print something to the console


// ==> (o) Inputs

// 
const Print_v1_Input_exec core.InputId = "exec"
// 
const Print_v1_Input_value core.InputId = "value"


// Outputs (o) ==> 

// 
const Print_v1_Output_exec core.OutputId = "exec"


