// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Github Action


// ==> (o) Inputs

// 
const Gh_action_v1_Input_env core.InputId = "env"


// Outputs (o) ==> 

// 
const Gh_action_v1_Output_exec core.OutputId = "exec"
// 
const Gh_action_v1_Output_exec_err core.OutputId = "exec-err"


