// Code generated by graph-runner. DO NOT EDIT.

package node_interfaces

import "actionforge/graph-runner/core"// Run executable


// ==> (o) Inputs

// 
const Run_exec_v1_Input_args core.InputId = "args"
// 
const Run_exec_v1_Input_env core.InputId = "env"
// 
const Run_exec_v1_Input_exec core.InputId = "exec"
// 
const Run_exec_v1_Input_path core.InputId = "path"
// 
const Run_exec_v1_Input_print core.InputId = "print"
// 
const Run_exec_v1_Input_stdin core.InputId = "stdin"


// Outputs (o) ==> 

// 
const Run_exec_v1_Output_exec_err core.OutputId = "exec-err"
// 
const Run_exec_v1_Output_exec_success core.OutputId = "exec-success"
// 
const Run_exec_v1_Output_exit_code core.OutputId = "exit_code"
// 
const Run_exec_v1_Output_output core.OutputId = "output"


