on: [push]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build and Publish
    permissions:
      packages: write
      contents: read
    steps:
      - name: Execute Action Graph
        uses: actionforge/action@v0.8.30
        with:
          graph_file: build-and-publish.yml

      - name: List
        run: ls -lsa

      - name: Run Integration test
        uses: actionforge/action@465201105622356df741319f16d60ffbf90d0462
        with:
          # graph-runner in workdir directory
          runner_path: ${{ github.workspace }}/graph-runner
          graph_file: test_env.yml
