on: [push]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build and Publish
    permissions:
      packages: write
      contents: read
    steps:
      - name: Execute Action Graph
        uses: actionforge/action@v0.8.30
        with:
          graph_file: build-and-publish.yml

      - name: List
        run: ls -lsa

      - name: Run Integration test
        uses: actionforge/action@6667acfef5cfb69d413683a8a87c1aa15412f649
        with:
          # Use graph-runner in workdir directory
          runner_path: ${{ github.workspace }}/graph-runner
          graph_file: test_env.yml
        env:
          MY_ENV: "hello world"
