on: [push]

jobs:
  build-test-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    name: Build and Publish
    permissions:
      packages: write
      contents: read
    steps:
      - name: Execute Action Graph
        uses: actionforge/action@46eca450335b4873aa06c1d5da7ded0f7654236c # v0.9.54
        with:
          graph_file: build.yml
        env:
          FREEZE_TEST: true

      - name: Test test_input_output.yml
        if: ${{ matrix.os != 'macos-latest' }}
        uses: actionforge/action@46eca450335b4873aa06c1d5da7ded0f7654236c # v0.9.54
        with:
          runner_path: ${{ github.workspace }}/graph-runner
          graph_file: test_input_output.yml

      - name: Test test_env.yml
        if: ${{ matrix.os != 'macos-latest' }}
        uses: actionforge/action@46eca450335b4873aa06c1d5da7ded0f7654236c # v0.9.54
        with:
          runner_path: ${{ github.workspace }}/graph-runner
          graph_file: test_env.yml
        env:
          MY_ENV: "hello world"

      - name: Build and Publish
        uses: actionforge/action@46eca450335b4873aa06c1d5da7ded0f7654236c # v0.9.54
        with:
          runner_path: ${{ github.workspace }}/graph-runner
          graph_file: publish.yml
          secrets: ${{ toJson(secrets) }}
